### ISSUE TITLE
되돌리기 오류

### ISSUE THREAD

**Issue by ghost** [namu-wiki/monaco-namu#10]
편집기에서 RAW 편집이나 미리보기 갔다가 다시 돌아오면 되돌리기가 안됩니다.
정확히는 이전 되돌리기 기록이 없어집니다.

**Comment by diphenhydramine-hydrochloride** [comment]
RAW편집으로 갔다가 돌아오면 편집기 내에서 Undo(Ctrl-Z) 기록이 사라져서 안 된다는 의미로 생각되는데 맞나요?

**Comment by ghost** [comment]
> RAW편집으로 갔다가 돌아오면 편집기 내에서 Undo(Ctrl-Z) 기록이 사라져서 안 된다는 의미로 생각되는데 맞나요?

네.

**Comment by ghost** [comment]
해결된 이슈.
