### ISSUE TITLE
단축키 오류

### ISSUE THREAD

**Issue by ghost** [namu-wiki/monaco-namu#11]
요약 쓰고 엔터 누를 때 저장되는 게 아니라 편집기 모드로 넘어갑니다.
편집기 상태에서는 반응이 없고요.

**Comment by diphenhydramine-hydrochloride** [comment]
엔터 눌렀을 때 저장이 안 된다는 건 알겠는데 편집기 모드로 넘어간다는 말이 무슨 뜻인지 잘 모르겠는데 설명좀 부탁드립니다.

**Comment by ghost** [comment]
> 엔터 눌렀을 때 저장이 안 된다는 건 알겠는데 편집기 모드로 넘어간다는 말이 무슨 뜻인지 잘 모르겠는데 설명좀 부탁드립니다.

RAW 편집 후 요약을 쓰고 엔터를 누르면 편집기 탭으로 넘어갑니다.

**Comment by ghost** [comment]
해결됨.
