### ISSUE TITLE
스크롤 관련하여 불편한 점

### ISSUE THREAD

**Issue by ghost** [namu-wiki/monaco-namu#15]
# 건의
버그인지 확실하지는 않지만, 모바일에서 스크롤을 하려면 키보드를 항상 올린 상태에서 스크롤을 해야 하는 불편함이 있습니다. 기존 RAW 편집기는 커서만 한번 올리면 키보드가 내려간 상태에도 스크롤이 가능했습니다.

**Comment by diphenhydramine-hydrochloride** [comment]
모바일 관련 Monaco Editor 자체 버그가 다수 있어 현재 모바일에서의 사용은 권장하지 않습니다.
